# SPDX-FileCopyrightText: 2026 彭旭
# SPDX-License-Identifier: AGPL-3.0-only
$file = "D:\桌面\跟进项目\U-Ai\记忆系统增强规划.md"
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# 项目记忆系统增强规划")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("---")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## 一、短期工作记忆层（对话窗口管理）")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("### 当前现状")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("项目目前的对话上下文管理位于 backend/internal/chat/service.go：loadHistory() 全量加载无窗口限制，ProcessMessage() 直接拼接全部历史，messages 表 include_in_context 字段闲置。")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("### 细化需求1：滑动窗口上下文管理器")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("- config.go：ChatConfig 新增 ContextWindowMaxRounds 字段，默认20")
[void]$sb.AppendLine("- config.yml：新增 contextWindowMaxRounds: 20")
[void]$sb.AppendLine("- service.go：loadHistory() 增加 WHERE include_in_context=1 + LIMIT 过滤，新增 getWindowMaxRounds()、trimContextWindow()")
[void]$sb.AppendLine("- sql.sql：新增 idx_messages_conv_ctx 索引")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("### 细化需求2：工作记忆缓存结构")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("- 新建 working_memory.go：WorkingMemory 结构体 + WorkingMemoryCache（mu+store+expireAfter）")
[void]$sb.AppendLine("- service.go：结构体加 wmCache 字段，ProcessMessage 注入+更新工作记忆")
[void]$sb.AppendLine("- model.go：新增 WorkingMemoryState 结构体")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("### 细化需求3：自动标记超出窗口的消息")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("- 由 trimContextWindow() 覆盖实现")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("### 改动影响范围汇总")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| config.go | 修改 | ChatConfig 加字段 |")
[void]$sb.AppendLine("| config.yml | 修改 | 加配置项 |")
[void]$sb.AppendLine("| service.go | 修改 | 7处改动 |")
[void]$sb.AppendLine("| sql.sql | 修改 | 新增索引 |")
[void]$sb.AppendLine("| working_memory.go | 新建 | 缓存实现 |")
[void]$sb.AppendLine("| model.go | 修改 | 新增结构体 |")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("**前端无需改动。**")
Write-Host "Written chapter 1"
[System.IO.File]::WriteAllText($file, $sb.ToString(), [System.Text.Encoding]::UTF8)
